In [1]:
import numpy as np

In [4]:
np.__version__

'1.15.4'

In [36]:
array = np.zeros((10))
print(array)
array[4]=1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
array.size*array.itemsize

240

In [31]:
??np.add

In [46]:
x = list(range(10,50))
x = np.array(x)

print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [83]:
x = list(range(16))
x = np.array(x)
x=x.reshape(2,2,2,2)
print(x.shape)
print(x)



(2, 2, 2, 2)
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [89]:

z = np.array([1,2,0,0,4,0])

print(np.nonzero(z))




(array([0, 1, 4], dtype=int64),)


In [99]:
np.eye(2,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0]])

In [128]:
x = np.random.randint(0,1,(15,15))

x[0,:]=1
x[:,0]=1
x[-1,:]=1
x[:,-1]=1
r,c = x.shape
y = np.zeros((r+6,c+6))
y[3:-3,3:-3]=x


print(y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0.

In [129]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [130]:
0 * np.nan

nan

In [131]:
np.nan == np.nan

False

In [132]:
np.inf > np.nan

False

In [133]:
np.nan - np.nan

nan

In [134]:
np.nan in set([np.nan])

True

In [145]:
[0 0 0 0 0
 1 0 0 0 0
 0 2 0 0 0
 0 0 3 0 0
 0 0 0 4 0]

0.30000000000000004

In [163]:
v =[1,2,3,4]

v = np.diag(v)
y =  np.zeros((5,5))
y[1:,0:-1]=v

print(y)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [165]:
y= np.zeros((8,8))



[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [191]:
y=np.zeros((8,8),dtype=int)



y[::2,::2]=1
y[1::2,1::2]=1


print(y)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [198]:
print(np.unravel_index(335,(6,7,8)))

(5, 6, 7)


In [210]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[ 1.55999371 -1.63182891 -1.05854528 -1.6715092   0.57267375]
 [-1.43732394 -0.36712446  0.21628805  0.47138176  0.85381259]
 [ 0.55992751  0.42968084  0.78994688  1.57054962  0.87381117]
 [ 0.53197242 -0.32771499 -0.16029918  1.50395603 -1.73748881]
 [-0.31215155 -0.15785195 -0.88690382  0.76969497 -0.95494719]]


In [212]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [217]:
Z = np.tile( np.array([[6,71],[10,0],[8,9]]), (6,4))
print(Z)

[[ 6 71  6 71  6 71  6 71]
 [10  0 10  0 10  0 10  0]
 [ 8  9  8  9  8  9  8  9]
 [ 6 71  6 71  6 71  6 71]
 [10  0 10  0 10  0 10  0]
 [ 8  9  8  9  8  9  8  9]
 [ 6 71  6 71  6 71  6 71]
 [10  0 10  0 10  0 10  0]
 [ 8  9  8  9  8  9  8  9]
 [ 6 71  6 71  6 71  6 71]
 [10  0 10  0 10  0 10  0]
 [ 8  9  8  9  8  9  8  9]
 [ 6 71  6 71  6 71  6 71]
 [10  0 10  0 10  0 10  0]
 [ 8  9  8  9  8  9  8  9]
 [ 6 71  6 71  6 71  6 71]
 [10  0 10  0 10  0 10  0]
 [ 8  9  8  9  8  9  8  9]]
